apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: GPU
  namespace: openshift-sro-operator
spec:
  schedulingType: "PriorityPreemption"
  priorityClasses:
  - apiVersion: scheduling.k8s.io/v1beta1
    kind: PriorityClass
    metadata:
      name: high-priority
    value: 1000000
    globalDefault: false
    description: "This priority class should be used for GPU service pods only."

