apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: openshift-sro
  name: nvidia-dcgm-exporter
spec:
  endpoints:
  - port: dcgm 
  jobLabel: app
  namespaceSelector:
    matchNames:
    - openshift-sro
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter

