apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-daemonset
  namespace: openshift-sro-operator
spec:
  selector:
    matchLabels:
      name: nvidia-driver-ds
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: nvidia-driver-ds
    spec:
      tolerations:
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      serviceAccount: nvidia-driver
      hostPID: true
      containers:
      - image: quay.io/zvonkok/nvidia-driver:v410.79-KERNEL_FULL_VERSION
        imagePullPolicy: Always
        name: nvidia-driver-ctr
        command: ["nvidia-driver"]
        args: ["init"]
        securityContext:
          privileged: true
          seLinuxOptions:
            level: "s0"
        volumeMounts:
          - name: run-nvidia
            mountPath: /run/nvidia
            mountPropagation: Bidirectional
          - name: config
            mountPath: /etc/containers/oci/hooks.d
          - name: host
            mountPath: /host
      volumes:
        - name: host
          hostPath:
            path: /
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
        - name: config
          configMap:
            name: nvidia-driver
            items:
              - key: oci-nvidia-hook-json
                path: oci-nvidia-hook.json
      nodeSelector:
        feature.node.kubernetes.io/pci-0300_10de.present: "true"
        feature.node.kubernetes.io/kernel-version.full: "KERNEL_FULL_VERSION"
