apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nvidia-driver-validation
  name: nvidia-driver-validation
  namespace: openshift-sro
spec:
  selector:
    matchLabels:
      app: nvidia-driver-validation
  template:
    metadata:
      labels:
        app: nvidia-driver-validation
    spec:
      containers:
      - image: quay.io/zvonkok/cuda-vector-add:v0.1
        imagePullPolicy: Always
        restartPolicy: OnFailure
        name: nvidia-driver-ctr
        resources:
          limits:
            nvidia.com/gpu: 1

      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true"
