apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nvidia-device-plugin-validation
  name: nvidia-device-plugin-validation
  namespace: openshift-sro
spec:
  selector:
    matchLabels:
      app: nvidia-device-plugin-validation
  template:
    metadata:
      labels:
        app: nvidia-device-plugin-validation
  spec:
    restartPolicy: Error
    containers:
      - name: cuda-vector-add
        image: "quay.io/zvonkok/cuda-vector-add:v0.1"
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
          - name: NVIDIA_REQUIRE_CUDA  
            value: "cuda>=5.0"
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
    nodeSelector:
      feature.node.kubernetes.io/pci-10de.present: "true"
